version: "3.8"

services:
  
  nextcloud_server:
    build: 
      dockerfile: Dockerfile.nextcloud_server
    depends_on:
      - nextclouddb
      - redis
      - elasticsearch
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html/
      - ./nextcloud_server/docker-entrypoint-hooks.d/post-installation:/docker-entrypoint-hooks.d/post-installation
      - ./nextcloud_server/docker-entrypoint-hooks.d/before-starting:/docker-entrypoint-hooks.d/before-starting
      - ./nextcloud_server/server:/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis
      # - NEXTCLOUD_ADMIN_USER=admin
      # - NEXTCLOUD_ADMIN_PASSWORD=password
      # - NEXTCLOUD_GUEST_USER=guest
      # - NEXTCLOUD_GUEST_PASSWORD=guest
      # - OPCACHE_ENABLE=0
      # - NEXTCLOUD_TRUSTED_DOMAINS=192.168.88.195:8080
      # - PHP_MEMORY_LIMIT=1024M
    env_file:
      - .env

  nextcloud_compiler:
    build: 
      context: .
      dockerfile: ./nextcloud_compiler/Dockerfile
    volumes:
      - ./nextcloud_compiler/src/apps:/src/apps
      - ./nextcloud_compiler/src/build:/src/build
      - ./nextcloud_compiler/src/core/src:/src/core/src
      - ./nextcloud_server/server/core/css:/src/core/css
      - ./nextcloud_server/server/core/img:/src/core/img
      - ./nextcloud_server/server/core/fonts:/src/core/fonts
      - ./nextcloud_server/server/core/doc:/src/core/doc
      - ./nextcloud_server/server/core/js:/src/core/js
      - ./nextcloud_server/server/core/templates:/src/core/templates
      - ./nextcloud_server/server/core/vendor:/src/core/vendor
      - ./nextcloud_server/server/dist:/src/dist
      - ./nextcloud_compiler/entrypoint.sh:/entrypoint.sh
    env_file:
      - .env

  nextclouddb:
    image: mariadb:11.6-ubi
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      
  redis:
    image: redis:7.2.7-alpine3.21

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    command: ["/entrypoint.sh"]
    environment:
      - discovery.type=single-node
      # - "ES_JAVA_OPTS=-Xms2g -Xmx4g"
      - xpack.security.enabled=false
      - xpack.security.http.ssl:enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/entrypoint.sh:/entrypoint.sh
    env_file:
      - .env

volumes:
  nextcloud:
  db:
  esdata:
