version: "3.8"

services:
  nextcloud:
    image: nextcloud
    depends_on:
      - nextclouddb
      - redis
      - elasticsearch
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html/
      - ./post-installation:/docker-entrypoint-hooks.d/post-installation
      - ./before-starting:/docker-entrypoint-hooks.d/before-starting
      - ./html:/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password

  nextclouddb:
    image: mariadb:11.6-ubi
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      
  redis:
    image: redis:7.2.7-alpine3.21

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    # ports:
    # 127.0.0.1:9200:9200 #only needed if you are connecting through a docker network
    command: sh -c "bin/elasticsearch-plugin install --batch ingest-attachment; /bin/tini -s /usr/local/bin/docker-entrypoint.sh eswrapper"
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx2048m"
    user: 1000:1000
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  nextcloud:
  db:
  elasticsearch:
